config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  # get "/login", to "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/map", to: "maps#index"

  resources :users
  resources :accidents
end

app/models/accident.rb
class Accident < ApplicationRecord
  belongs_to :user

  scope :waiting, ->{where status: false}
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

  def remember
    self.remember_token = Admin.new_token
    update_attributes remember_digest: Admin.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum gender: {other: 2, female: 1, male: 0}

  has_many :accidents, dependent: :destroy

  validates :email, presence: true, length: {maximum: 255},
    uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/accidents_controller.rb
class AccidentsController < ApplicationController
  before_action :find_user

  def new
    @accident = Accident.new
  end

  def create
    @accident = Accident.new accidents_params
    if @accident.save
  end

  private
  def accidents_params
    params.require(:accident).permit(:latitude, :longitude).merge user_id:
      user.id
  end

  def find_user
    @user = User.find_by phone: params[:phone]
    if @user.nil?
      flash[:danger] = t "flash.user_not_found"
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = t "flash.must_logged_in"
      redirect_to root_path
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @accident = Accident.waiting
    @hash = Gmaps4rails.build_markers(@accident) do |accident, marker|
      marker.lat accident.latitude
      marker.lng accident.longitude
      marker.infowindow accident.user.description
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by email:params[:session][:email].downcase
    if admin && admin.authenticate(params[:session][:password])
      log_in admin
      params[:session][:remember_me] == "1" ? remember(admin) : forget(admin)
      redirect_to users_path
    else
      flash.now[:danger] = t "flash.invalid_login"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :find_user, except: [:index, :new, :create]

  def index
    @users = if user_name = params[:phone]
      User.phone_like user_phone
    else
      User.all
    end.paginate page: params[:page], per_page: 10
  end

  def new
     @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.activate
      flash[:info] = t "flash.add_user_success"
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "flash.update_user_success"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = t "flash.delete_user"
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :phone, :password,
      :password_confirmation, :admin
  end

  def find_user
    @user = User.find_by id: params[:id]
    if @user.nil?
      flash[:danger] = t "flash.user_not_found"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = " "
    base_title = t "layouts.base_title"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in admin
    session[:admin_id] = admin.id
  end

  def current_admin
    if admin_id = session[:admin_id]
      @current_user ||= Admin.find_by id: admin_id
    elsif admin_id = cookies.signed[:admin_id]
      admin = Admin.find_by id: admin_id
      if admin && admin.authenticated?(:remember, cookies[:remember_token])
        log_in admin
        @current_admin = admin
      end
    end
  end

  def remember admin
    admin.remember
    cookies.permanent.signed[:admin_id] = admin.id
    cookies.permanent[:remember_token] = admin.remember_token
  end

  def forget admin
    admin.forget
    cookies.delete :admin_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def logged_in?
    current_admin.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".name" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"), "/static_pages/about"%></li>
      <li><%= link_to t("static_pages.contact.title"), "/static_pages/contact" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-customer">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
        data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <nav class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", map_path %></li>
        <li><%= link_to "User", users_path %></li>
        <li><%= link_to "Accident", "#" %></li>
        <li><%= link_to t("layouts.header.logout"), logout_path,
          method: "delete" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
  </head>
  <body>
    <% if logged_in? %>
      <%= render "layouts/header" %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
        <% end %>
        <%= yield %>
        <%= render "layouts/footer" %>
      </div>
    <% else %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
        <% end %>
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>

app/views/maps/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyAjsc1tn7rw0aBLMbo0FEPGWRbwHbxHAdg"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<div style='width: 100%;'>
  <div id="map" style='width: 1170px; height: 500px'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/users/_form.html.erb
<%= form_for @user, url: yield(:url_path) do |f| %>
  <div class="form-group">
    <%= render "shared/error_messages", object: f.object %>
  </div>
  <div class="form-group">
    <%= f.label t("admin.users.index.email") %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("admin.users.index.name") %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("admin.users.index.phone") %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_search_form.html.erb
<%= form_tag users_path, method: :get do %>
  <div class="input-group">
    <%= text_field_tag :name, params[:name], class: "form-control",
      placeholder: t(".placeholder_user") %>
    <span class="input-group-btn">
      <%= submit_tag t(".search"), class: "btn btn-default" %>
    </span>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.phone %></td>
  <td><%= user.gender %></td>
  <td><%= user.blood_group %></td>
  <td>
    <%= link_to t(".edit"), edit_user_path(user), class: "btn btn-info" %>
  </td>
  <td>
    <%= link_to t("delete"), user_path(user), class: "btn btn-danger",
      method: :delete, data: {confirm: t("data.confirm")} %>
  </td>
</tr>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :url_path, user_path(@user) %>
<% provide :button_text, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row margin-bottom-10">
  <div class="col-md-6">
    <%= link_to t(".add_user"), new_user_path, class: "btn btn-primary" %>
  </div>
  <div class="col-md-6 pull-right">
    <%= render "search_form" %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-responsive table-striped table-bordered">
      <thead>
        <tr>
          <th><%= t ".name" %></th>
          <th><%= t ".email" %></th>
          <th><%= t ".phone" %></th>
          <th><%= t ".gender" %></th>
          <th><%= t ".blood_group" %></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @users %>
      </tbody>
    </table>
  </div>
  <div class="col-md-12 text-center">
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<% provide :url_path, users_path %>
<% provide :button_text, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>